// нужны юскейсы для rpc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/url_shortner.proto

package url_shortner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenReq) Reset() {
	*x = ShortenReq{}
	mi := &file_api_url_shortner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenReq) ProtoMessage() {}

func (x *ShortenReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenReq.ProtoReflect.Descriptor instead.
func (*ShortenReq) Descriptor() ([]byte, []int) {
	return file_api_url_shortner_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenReq) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResp) Reset() {
	*x = ShortenResp{}
	mi := &file_api_url_shortner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResp) ProtoMessage() {}

func (x *ShortenResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResp.ProtoReflect.Descriptor instead.
func (*ShortenResp) Descriptor() ([]byte, []int) {
	return file_api_url_shortner_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReq) Reset() {
	*x = ResolveReq{}
	mi := &file_api_url_shortner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReq) ProtoMessage() {}

func (x *ResolveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReq.ProtoReflect.Descriptor instead.
func (*ResolveReq) Descriptor() ([]byte, []int) {
	return file_api_url_shortner_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveReq) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResp) Reset() {
	*x = ResolveResp{}
	mi := &file_api_url_shortner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResp) ProtoMessage() {}

func (x *ResolveResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResp.ProtoReflect.Descriptor instead.
func (*ResolveResp) Descriptor() ([]byte, []int) {
	return file_api_url_shortner_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResp) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_api_url_shortner_proto protoreflect.FileDescriptor

const file_api_url_shortner_proto_rawDesc = "" +
	"\n" +
	"\x16api/url_shortner.proto\x12\furl_shortner\"/\n" +
	"\n" +
	"ShortenReq\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"*\n" +
	"\vShortenResp\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\")\n" +
	"\n" +
	"ResolveReq\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"0\n" +
	"\vResolveResp\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\x8d\x01\n" +
	"\vURLShortner\x12>\n" +
	"\aShorten\x12\x18.url_shortner.ShortenReq\x1a\x19.url_shortner.ShortenResp\x12>\n" +
	"\aResolve\x12\x18.url_shortner.ResolveReq\x1a\x19.url_shortner.ResolveRespB\x1cZ\x1a./internal/pb/url_shortnerb\x06proto3"

var (
	file_api_url_shortner_proto_rawDescOnce sync.Once
	file_api_url_shortner_proto_rawDescData []byte
)

func file_api_url_shortner_proto_rawDescGZIP() []byte {
	file_api_url_shortner_proto_rawDescOnce.Do(func() {
		file_api_url_shortner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_url_shortner_proto_rawDesc), len(file_api_url_shortner_proto_rawDesc)))
	})
	return file_api_url_shortner_proto_rawDescData
}

var file_api_url_shortner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_url_shortner_proto_goTypes = []any{
	(*ShortenReq)(nil),  // 0: url_shortner.ShortenReq
	(*ShortenResp)(nil), // 1: url_shortner.ShortenResp
	(*ResolveReq)(nil),  // 2: url_shortner.ResolveReq
	(*ResolveResp)(nil), // 3: url_shortner.ResolveResp
}
var file_api_url_shortner_proto_depIdxs = []int32{
	0, // 0: url_shortner.URLShortner.Shorten:input_type -> url_shortner.ShortenReq
	2, // 1: url_shortner.URLShortner.Resolve:input_type -> url_shortner.ResolveReq
	1, // 2: url_shortner.URLShortner.Shorten:output_type -> url_shortner.ShortenResp
	3, // 3: url_shortner.URLShortner.Resolve:output_type -> url_shortner.ResolveResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_url_shortner_proto_init() }
func file_api_url_shortner_proto_init() {
	if File_api_url_shortner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_url_shortner_proto_rawDesc), len(file_api_url_shortner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_url_shortner_proto_goTypes,
		DependencyIndexes: file_api_url_shortner_proto_depIdxs,
		MessageInfos:      file_api_url_shortner_proto_msgTypes,
	}.Build()
	File_api_url_shortner_proto = out.File
	file_api_url_shortner_proto_goTypes = nil
	file_api_url_shortner_proto_depIdxs = nil
}
