// нужны юскейсы для rpc

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/url_shortner.proto

package url_shortner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLShortner_Shorten_FullMethodName = "/url_shortner.URLShortner/Shorten"
	URLShortner_Resolve_FullMethodName = "/url_shortner.URLShortner/Resolve"
)

// URLShortnerClient is the client API for URLShortner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLShortnerClient interface {
	Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error)
	Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error)
}

type uRLShortnerClient struct {
	cc grpc.ClientConnInterface
}

func NewURLShortnerClient(cc grpc.ClientConnInterface) URLShortnerClient {
	return &uRLShortnerClient{cc}
}

func (c *uRLShortnerClient) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortenResp)
	err := c.cc.Invoke(ctx, URLShortner_Shorten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortnerClient) Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResp)
	err := c.cc.Invoke(ctx, URLShortner_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLShortnerServer is the server API for URLShortner service.
// All implementations must embed UnimplementedURLShortnerServer
// for forward compatibility.
type URLShortnerServer interface {
	Shorten(context.Context, *ShortenReq) (*ShortenResp, error)
	Resolve(context.Context, *ResolveReq) (*ResolveResp, error)
	mustEmbedUnimplementedURLShortnerServer()
}

// UnimplementedURLShortnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLShortnerServer struct{}

func (UnimplementedURLShortnerServer) Shorten(context.Context, *ShortenReq) (*ShortenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (UnimplementedURLShortnerServer) Resolve(context.Context, *ResolveReq) (*ResolveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedURLShortnerServer) mustEmbedUnimplementedURLShortnerServer() {}
func (UnimplementedURLShortnerServer) testEmbeddedByValue()                     {}

// UnsafeURLShortnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLShortnerServer will
// result in compilation errors.
type UnsafeURLShortnerServer interface {
	mustEmbedUnimplementedURLShortnerServer()
}

func RegisterURLShortnerServer(s grpc.ServiceRegistrar, srv URLShortnerServer) {
	// If the following call pancis, it indicates UnimplementedURLShortnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLShortner_ServiceDesc, srv)
}

func _URLShortner_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortnerServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortner_Shorten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortnerServer).Shorten(ctx, req.(*ShortenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortner_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortnerServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortner_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortnerServer).Resolve(ctx, req.(*ResolveReq))
	}
	return interceptor(ctx, in, info, handler)
}

// URLShortner_ServiceDesc is the grpc.ServiceDesc for URLShortner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLShortner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "url_shortner.URLShortner",
	HandlerType: (*URLShortnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _URLShortner_Shorten_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _URLShortner_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/url_shortner.proto",
}
